# Generated by Django 4.0.5 on 2023-02-19 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='image_author_link',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='image_author_name',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='image_website_link',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='image_website_name',
        ),
    ]
